spring:
  application:
    name:ecom-application
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomdb
    username: embarkx
    password: embarkx
  jpa:
    datasource: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    datasource-platform: org.hibernate.dialect.PostgreSQLDialect


#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#
#    jpa:
#      database-platform: org.hibernate.dialect.H2Dialect
#      hibernate:
#        ddl-auto: update
#      show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
